# Generated by Django 6.0.1 on 2026-02-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('NEWS', 'News'), ('REVIEW', 'Review'), ('MERCH', 'Merchandise'), ('EVENT', 'Event')], default='NEWS', max_length=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
