# Generated by Django 6.0.3 on 2026-03-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('NEWS', 'News'), ('REVIEW', 'Review'), ('MERCH', 'Merchandise'), ('EVENT', 'Event')], db_index=True, default='NEWS', max_length=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
