# Generated by Django 6.0.3 on 2026-03-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_add_database_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_url',
            field=models.URLField(blank=True, help_text='Original source URL', max_length=500, null=True),
        ),
    ]
